SlotMachine\SlotBundle\Entity\Card:
    type: entity
    table: card
    repositoryClass: SlotMachine\SlotBundle\Entity\CardRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        reelIndex:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: reel_index
        value:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        alias:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        reel:
            targetEntity: SlotMachine\SlotBundle\Entity\Reel
            cascade: {  }
            mappedBy: null
            inversedBy: cards
            joinColumns:
                reel:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
