parameters:
#    slot_machine_slot.example.class: SlotMachine\SlotBundle\Example

services:
#    slot_machine_slot.example:
#        class: %slot_machine_slot.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
