<?php

namespace SlotMachine\SlotBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReelRepository extends EntityRepository
{
}
